name: CI - Teste e Build da Extensão

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: npm ci

      # 4. Instala as dependências do Playwright (navegadores)
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      # 5. Roda o script de build e os testes
      - name: Run build and tests
        run: npm test

      # 6. Publica o relatório de testes (sempre, mesmo se os testes falharem)
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      # 7. Publica o arquivo .zip da extensão (apenas se tudo passar)
      - name: Upload extension package
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: dist/extension.zip
          retention-days: 30